### ISSUE TITLE
How many businesses across the North have B Corp status?

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#12]
We have permission to use the B corp registry data, so we can calculate this.

We have presented a hex-map [here](https://open-innovations.github.io/true-north/themes/true-north/b-corporations/) of where they are located in the UK by local authority, broken down by business size, owner type etc.

We could add a "Total in the North" dashboard panel to answer this Q directly @slowe 

Since we have data on this, we would appreciate more input on exactly what Brabners want to show from it.

**Comment by slowe** [comment]
@luke-strange Yep, I think a "total in the North" would work on a dashboard panel. I could either add as an output from the current B corp processing or some other pipeline could use the LA codes in the CSV output file to work it out.

Having a "total in the North" would also allow a "% of B corps who are part of True North" panel too if we know how many B corps are in True North.

**Comment by luke-strange** [comment]
@slowe 

1) Please can you add "total B Corps in the North" as an output from the current processing. This saves us making another pipeline with a chain of dependencies.

2) I think True North is a 'per person' sign up, whereas B Corp is for an entire organisation. I confirmed this yesterday with Brabners. We could do instead "% of B corps that have at least one employee who is part of True North". Let me know what you think.

**Comment by slowe** [comment]
@luke-strange
1. Yep. Where should a "total B Corps in the North" be saved?
2. Probably. Are you able to get the number of B corps with at least one employee?

**Comment by luke-strange** [comment]
@slowe 

1) Please save it in `src/_data/dashboard/`, as I think we will show it on the front page. At some point we may want to append this to a master csv that drives the dashboard from one file. That's something to sort out when we have an updated / consistent file for the "True North list", which I am waiting for at the moment.

2) In the True north list, there is a column called "Company name". We could make a unique list of these, and compare it to the B-Corp companies names. This may be hard given the name differences that may occur. If that doesn't work, we could use the "Is your organisation currently a B Corp or in the process of joining?" column, although this may not be completely accurate as the employees might not know if their organisation is a B-corp (less likely) or if they are planning to join (more likely).

**Comment by slowe** [comment]
@luke-strange I've done point 1.

**Comment by luke-strange** [comment]
I'm going to add a visualisation for this on the dashboard. Then I will close the issue and add point 2 as a new issue.

**Comment by luke-strange** [comment]
Point 1 has been done, Point 2 is actually already covered on the panel dashboard. Closing the ticket.
