### ISSUE TITLE
With regard to sectors, how many vacancies are there?

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#2]
We have monthly data on vacancies growth by sector, nationally. 

Now I am looking at this question again, I think we also need absolute values please @ChristianSpence .

**Comment by ChristianSpence** [comment]
Nominal values are in EDD in `LMS.parquet`. You'll need `variable.code IN "JP9[H-Y]"`. I don't know how python handles regex, but basically all variable codes from `JP9H` to `JP9Y`, incrementing the last character alphabetically. Data is available monthly, quarterly and annually, so don't forget to set a filter on `dates.freq`.

Also available in LMS are normalised values, vacancies per _x_000 jobs.

**Comment by luke-strange** [comment]
Data has been read and added to repo, now need to pivot it and clean slightly for visualisation.
