### ISSUE TITLE
All datasets down to LA level

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#26]
"Where possible we want to make sure the data is hyper-localised so we can compare very specific areas."

I think for now let's go with local authority level for every dataset where that exists. 

We can discuss if we want to go below this, e.g. to wards or PCONs. It gets a bit tricky depending what's available though.

**Comment by ChristianSpence** [comment]
@luke-strange all NOMIS data (labour market, skills, etc.) that was in the `working/cs/cs-true-north.[parquet|csv]` is now replicated but for all LADs in the North in `working/cs/nomis-lad.[parquet|csv]`
