### ISSUE TITLE
Geographic reach of true north

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#43]
- [ ] Work out % of northern LAs that contain at least one true north member.
- [ ] add this to dashboard
- [ ] put the TN members on a svg map with pins to show where they are.

**Comment by luke-strange** [comment]
@slowe has been making a list of the True north company numbers. From this, we can find their registered addresses and determine which local authority they are in.

Then, we can calculate the percentage of local authorities in the North (the 3 northern ITL 1 regions) that have at least one true north member.

**Comment by slowe** [comment]
I'm not sure it will be sensible to put pins on an SVG map as it isn't zoomable and they'll be on top of each other. Also, we are unlikely to have precise enough locations.

**Comment by slowe** [comment]
@luke-strange Any thoughts on how we progress on assigning True North members to local authorities in a way that will work going into the future? I don't think my by-hand process is going to work.

**Comment by luke-strange** [comment]
@slowe not as of yet. I think we will have to leave this for now and revisit.

**Comment by luke-strange** [comment]
I think for now, I am just going to make a bar chart based on the "City" column
