### ISSUE TITLE
Fix search bar colours on hex maps

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#46]
When you search for a local authority on the hex map, the text of the results is invisible (see image).

I inspected the element, and the reason is because the element has the same `color` and `background-colour` so it appears invisible.

![Image](https://github.com/open-innovations/true-north/assets/92686634/80cda2b6-9d33-4ec3-84df-4ec7a0fa3e04)

**Comment by slowe** [comment]
@luke-strange Yes, this was a knock on issue from a fix for something else in OI Lume Viz v0.15.3/4. Update to use v0.15.5.
