### ISSUE TITLE
Department for levelling up data

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#48]
Go through each grant and work out which local authority(s) they are in. 

For those with multiple LAs, divide the grant equally between them.

Also want to show the £ per person, so need LA population data.

**Comment by luke-strange** [comment]
I think this would be good to include under the purpose and social impact theme:

'This group will focus on developing initiatives that deliver purpose and social impact for the benefit of underserved communities across the North'

**Comment by slowe** [comment]
I've added Round 2 data and adjusted my code to create extra formatted columns to avoid "null" values.
