### ISSUE TITLE
Add UK business count data visualisation

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#55]
It will live in Purpose & Social Impact as a standalone page for now.

- [x] The data to drive the vis should sit in `src/themes/purpose-social-impact/non-profit/_data`. flat data file is in `working/cs/ukbc_lu.csv`
- [x] Will be a hex map by LA, showing the total number of "Non-profit body or mutual association" per Local Authority 2021 district.
- [x] Colour by the total
- [x] Show the top (n) sector name(s) in the tooltip.
- [x] As headlines, we should show the total number of non-profits in the UK, the total in the North, % of Uk business that are non-profit.
- [x] bar chart showing number of each size of company.

**Comment by slowe** [comment]
We don't have data on the whole of the UK, just The North. So the headlines will have to be limited to the number and percentage of northern businesses that are non-profit.

**Comment by slowe** [comment]
@luke-strange I think I've done as much as I can for each of the tasks.

**Comment by luke-strange** [comment]
Thanks, will close this.
