### ISSUE TITLE
Fix the employment hex maps

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#56]
it seems there's a slight discrepancy between the data and the hex 2023 layout e.g. "Cumberland" and "Westmorland an Furness" and "North Yorkshire" don't seem to be present in the data

![Image](https://github.com/open-innovations/true-north/assets/92686634/7327f972-4d47-4268-a11c-b5097d4891ed)

However, when using 2021 boundaries even more are missing:

![Image](https://github.com/open-innovations/true-north/assets/92686634/364cafd7-ecb7-4755-84b8-78c1bb0e16be)

@ChristianSpence is going to check his Nomis API call.

**Comment by ChristianSpence** [comment]
API call rewritten to use all LAD21 within RGN21 E1200000[1|2|3]. Will include both upper and lower tier LADs, but the lume-viz hex should drop those it doesn't need.

@luke-strange let me know if any issues
