### ISSUE TITLE
Can the hexmaps include a thicker border to identify the three northern ITL regions

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/true-north#60]
Almost certainly one for @slowe when he's back from his yurt.

**Comment by luke-strange** [comment]
This is something we actually discussed before @slowe . 

Brabners asked if we can put a border around the North on the hex maps.

I think they predominantly want to see this when the data is presented for the whole of the UK, but we should ask them if they also want the border present if the data is just the North.


excuse by poor hand drawn example: 

![Image](https://github.com/open-innovations/true-north/assets/92686634/c28c9fb8-7344-4e16-b842-3590b7a4f1c0)

**Comment by ChristianSpence** [comment]
I think the request was not just for the North, but for the borders of each ITL1 region that makes up the north
