### ISSUE TITLE
b-corp.pl won't get the correct number of UK b corps

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#65]
When I run b-corp.pl it says there are 2095 B-corps in the UK. However, a quick look on the B Corp website shows there are 2162.

![Screenshot 2024-08-09 at 09 54 41](https://github.com/user-attachments/assets/4ca545eb-fbe3-4167-9b9f-5405d6853965)

**Comment by slowe** [comment]
This is what their "API" is returning (well, 2116 as of today). It looks as though they've changed how they build their search results. The "old" API is still seemingly being updated but not as up-to-date as their website. It is not clear to me that using their new method will be good for multiple reasons. I'm not sure some links will be stable and may need to be different at different times. Also, some of the data now looks like it needs individual requests per company. That would switch us from 5 requests to >2100 requests which is a very different approach. For now, I'd rather stay with something a little behind their live site than switch to an approach that is going to lead to us making vast numbers of requests to them. Ultimately, it would be best if they had an actual data download that was stable.

**Comment by slowe** [comment]
@luke-strange Oh. I was wrong there about needing that many requests. There is a new "API" end point but it can return more results. However the data structure has changed a little.

I seem to get no postcode errors now which either means they've improved their source data or I've done something wrong. There are now more northern B-corps (351 compared to 210) for some reason and they are a bit more concentrated in specific local authorities e.g. Stockton-on-Tees had 2 before and now has none. Perhaps HQ postcodes have changed quite a bit?

Before:
![Screenshot 2024-08-13 at 10-23-25 B Corporations True North Data Explorer](https://github.com/user-attachments/assets/8d75022b-a9ab-4eec-964a-5538d4a1e566)

After:
![Screenshot 2024-08-13 at 10-23-20 B Corporations True North Data Explorer](https://github.com/user-attachments/assets/10ea89fd-6eb3-4398-9916-2ef886a6ec53)

**Comment by slowe** [comment]
@luke-strange Doh! There was something going wrong with my new "API" requests. Fixed and it looks much more like before.
